doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'Central\Migrations': '%kernel.project_dir%/migrations/Central'
    enable_profiler: false
