central:
    resource:
        path: ../src/Central/Controller/
        namespace: App\Central\Controller
    type: attribute

tenant:
    resource:
        path: ../src/Tenant/Controller/
        namespace: App\Tenant\Controller
    type: attribute
